### ISSUE TITLE
Read, sign, and return an Invention Agreement

### ISSUE THREAD

**Issue by burrage** [curiouslearning/workshop_tap_explore_2#3]
You may have completed this task already from the pre-workshop e-mail-- move to "Done" if so!

---------

Read the [Invention Agreement](https://docs.google.com/document/d/1BHNxggUfVBXfTT7M0jHVkguy1DLyED8PPHNPQy6s42c/edit?usp=sharing).

If you have questions regarding the agreement, please read the [Licensing FAQ](https://docs.google.com/document/d/1Q-ByHTYuoUsamhQcaHboyffCtBNu62j-0UkdVGtkqtI/edit?usp=sharing), and contact the course PM @bburrage on Slack if you have any further questions or concerns.

When you’re ready to sign and return: 

- In Google Docs, select “File” -> “Make A Copy” to save it to your Google Drive.
- Fill out your name and address marked in blue and digitally sign where it says “Workshop Participant”.
- Copy a link to the signed document and comment with the link below.

**Comment by audreygehring** [comment]
https://drive.google.com/open?id=0B5KYvr3SchhAQ3VDRkt4NkhnWnc
