### ISSUE TITLE
Conduct user testing session(s)

### ISSUE THREAD

**Issue by burrage** [curiouslearning/workshop_tap_explore_2#31]
Please read over [the following document](https://drive.google.com/open?id=1uOWlF4pZqYn4c9yVkLotlZ3LFPSHrzdLvJbpeWvgfUQ) in full and then follow [this set of instructions](https://docs.google.com/document/d/1uOWlF4pZqYn4c9yVkLotlZ3LFPSHrzdLvJbpeWvgfUQ/edit#heading=h.1iisqav4uwu0) within the document to conduct a user testing session. Be sure to take notes during the session to complete the next assignment.

**Comment by audreygehring** [comment]
Link to user testing reflection: https://docs.google.com/document/d/18cGNFeVW4zcROgSW3YG6EqqfO60eohgQYHZeo0dskrM/edit?usp=sharing
